package perforce

import (
	"fmt"
	"text/template"

	"github.com/jpvelasco/fabrica/internal/userdata"
)

// UserDataConfig is the input shape for the cloud-init script.
type UserDataConfig struct {
	Version    string // "latest", "2024.2", or "2024.2/2659294"
	ServerID   string // e.g. "fabrica-perforce"
	AdminPass  string // generated by create command
	DataDevice string // e.g. "/dev/nvme1n1"
	DataMount  string // "/hxdepots"
}

var userDataRenderer = userdata.New(template.Must(template.New("userdata").Parse(`#!/bin/bash
set -euo pipefail

wget -qO - https://package.perforce.com/perforce.pubkey | apt-key add -
add-apt-repository "deb http://package.perforce.com/apt/ubuntu jammy release"
apt-get update -qq
{{ if eq .Version "latest" -}}
apt-get install -y helix-p4d
{{- else -}}
apt-get install -y "helix-p4d={{ .Version }}"
{{- end }}

mkfs.ext4 {{ .DataDevice }}
mkdir -p {{ .DataMount }} /hxlogs /hxmetadata
mount {{ .DataDevice }} {{ .DataMount }}
echo "{{ .DataDevice }} {{ .DataMount }} ext4 defaults,nofail 0 2" >> /etc/fstab

/opt/perforce/sbin/configure-helix-p4d.sh \
  -n {{ .ServerID }} -p 1666 -r {{ .DataMount }} \
  -u admin --super-passwd "{{ .AdminPass }}" -y

systemctl enable helix-p4d
systemctl start helix-p4d
`)))

// applyDefaults fills zero-value fields with module defaults.
// Does not validate required fields — use validate before calling.
func (cfg *UserDataConfig) applyDefaults() {
	if cfg.DataDevice == "" {
		cfg.DataDevice = "/dev/nvme1n1"
	}
	if cfg.DataMount == "" {
		cfg.DataMount = "/hxdepots"
	}
	if cfg.ServerID == "" {
		cfg.ServerID = "fabrica-perforce"
	}
}

// validate checks required fields. Call after applyDefaults.
func (cfg *UserDataConfig) validate() error {
	if cfg.AdminPass == "" {
		return fmt.Errorf("AdminPass must not be empty")
	}
	return nil
}

// GenerateRaw renders the cloud-init script without base64 encoding.
// Used in tests to inspect the script content directly.
func GenerateRaw(cfg UserDataConfig) (string, error) {
	cfg.applyDefaults()
	if err := cfg.validate(); err != nil {
		return "", err
	}
	return userDataRenderer.Render(cfg)
}

// Generate renders the cloud-init user data script and returns it base64-encoded
// (the format EC2 expects for UserData in Cloud Control).
func Generate(cfg UserDataConfig) (string, error) {
	cfg.applyDefaults()
	if err := cfg.validate(); err != nil {
		return "", err
	}
	return userDataRenderer.RenderBase64(cfg)
}
