package perforce

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"text/template"
)

// UserDataConfig is the input shape for the cloud-init script.
type UserDataConfig struct {
	Version    string // "latest", "2024.2", or "2024.2/2659294"
	ServerID   string // e.g. "fabrica-perforce"
	AdminPass  string // generated by create command
	DataDevice string // e.g. "/dev/nvme1n1"
	DataMount  string // "/hxdepots"
}

var userDataTmpl = template.Must(template.New("userdata").Parse(`#!/bin/bash
set -euo pipefail

wget -qO - https://package.perforce.com/perforce.pubkey | apt-key add -
add-apt-repository "deb http://package.perforce.com/apt/ubuntu jammy release"
apt-get update -qq
{{ if eq .Version "latest" -}}
apt-get install -y helix-p4d
{{- else -}}
apt-get install -y "helix-p4d={{ .Version }}"
{{- end }}

mkfs.ext4 {{ .DataDevice }}
mkdir -p {{ .DataMount }} /hxlogs /hxmetadata
mount {{ .DataDevice }} {{ .DataMount }}
echo "{{ .DataDevice }} {{ .DataMount }} ext4 defaults,nofail 0 2" >> /etc/fstab

/opt/perforce/sbin/configure-helix-p4d.sh \
  -n {{ .ServerID }} -p 1666 -r {{ .DataMount }} \
  -u admin --super-passwd "{{ .AdminPass }}" -y

systemctl enable helix-p4d
systemctl start helix-p4d
`))

// GenerateRaw renders the cloud-init script without base64 encoding,
// applying defaults for any unset fields. Used in tests to inspect the
// script content directly.
func GenerateRaw(cfg UserDataConfig) (string, error) {
	if cfg.DataDevice == "" {
		cfg.DataDevice = "/dev/nvme1n1"
	}
	if cfg.DataMount == "" {
		cfg.DataMount = "/hxdepots"
	}
	if cfg.ServerID == "" {
		cfg.ServerID = "fabrica-perforce"
	}
	if cfg.AdminPass == "" {
		return "", fmt.Errorf("AdminPass must not be empty")
	}

	var buf bytes.Buffer
	if err := userDataTmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering userdata template: %w", err)
	}
	return buf.String(), nil
}

// Generate renders the cloud-init user data script and returns it base64-encoded
// (the format EC2 expects for UserData in Cloud Control).
func Generate(cfg UserDataConfig) (string, error) {
	raw, err := GenerateRaw(cfg)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString([]byte(raw)), nil
}
