package perforce

import (
	"fmt"
	"text/template"

	"github.com/jpvelasco/fabrica/internal/userdata"
)

// UserDataConfig is the input shape for the cloud-init script.
type UserDataConfig struct {
	Version    string // "latest", "2025.2", or "2024.2/2659294"
	ServerID   string // e.g. "fabrica-perforce"
	AdminPass  string // generated by create command
	DataDevice string // optional explicit device; empty = auto-detect (never the root disk)
	DataMount  string // "/hxdepots"
}

var userDataRenderer = userdata.New(template.Must(template.New("userdata").Parse(`#!/bin/bash
set -euo pipefail

ADMIN_PASS="{{ .AdminPass }}"
SERVER_ID="{{ .ServerID }}"
DATA_MOUNT="{{ .DataMount }}"

wget -qO - https://package.perforce.com/perforce.pubkey | apt-key add -
add-apt-repository "deb http://package.perforce.com/apt/ubuntu jammy release"
apt-get update -qq
{{ if eq .Version "latest" -}}
apt-get install -y helix-p4d
{{- else -}}
# Pinned versions rot out of Perforce's release archive; fall back to the
# current repo version rather than failing the whole bootstrap.
if ! apt-get install -y "helix-p4d={{ .Version }}"; then
  echo "WARNING: helix-p4d {{ .Version }} unavailable in the Perforce jammy repo — falling back to the latest available version"
  apt-get install -y helix-p4d
fi
{{- end }}

# Identify the data volume: the largest disk that is not the root disk.
# NVMe enumeration order is NOT deterministic across EC2 launches, so a
# hardcoded /dev/nvmeXnY can point at the root disk.
{{ if .DataDevice -}}
DATA_DEVICE="{{ .DataDevice }}"
echo "Using configured data device: $DATA_DEVICE"
{{- else }}
ROOT_SRC="$(findmnt -n -o SOURCE /)"
ROOT_DISK="$(lsblk -no PKNAME "$ROOT_SRC")"
DATA_DEVICE=""
DATA_SIZE=0
while read -r name size fstype; do
  [ "$name" = "$ROOT_DISK" ] && continue
  [ "$fstype" != "" ] && continue
  bytes=$(lsblk -bn -o SIZE "/dev/$name")
  if [ "$bytes" -gt "$DATA_SIZE" ]; then DATA_DEVICE="/dev/$name"; DATA_SIZE=$bytes; fi
done <<EOF
$(lsblk -dn -o NAME,SIZE,FSTYPE)
EOF
if [ -z "$DATA_DEVICE" ]; then
  echo "ERROR: no unformatted data volume found besides root ($ROOT_DISK)" >&2
  exit 1
fi
echo "Using data device: $DATA_DEVICE"
{{- end }}

mkfs.ext4 "$DATA_DEVICE"
mkdir -p "$DATA_MOUNT" /hxlogs /hxmetadata
mount "$DATA_DEVICE" "$DATA_MOUNT"
echo "$DATA_DEVICE $DATA_MOUNT ext4 defaults,nofail 0 2" >> /etc/fstab

# Perforce split Helix Core into the p4-server packages in 2026.1: the
# configure script dropped --super-passwd/-y for a positional service name +
# -P password, and instances are managed via p4dctl instead of a helix-p4d
# systemd unit. Detect the generation at runtime — the installed version can
# differ from the requested pin when the archive has dropped it.
CONFIGURE=/opt/perforce/sbin/configure-helix-p4d.sh
[ -x "$CONFIGURE" ] || CONFIGURE=/opt/perforce/sbin/configure-p4d.sh

if "$CONFIGURE" --help 2>&1 | grep -q -- '--super-passwd'; then
  "$CONFIGURE" -n "$SERVER_ID" -p 1666 -r "$DATA_MOUNT" \
    -u admin --super-passwd "$ADMIN_PASS" -y
else
  "$CONFIGURE" "$SERVER_ID" -n -p 1666 -r "$DATA_MOUNT" \
    -u admin -P "$ADMIN_PASS"
fi

# Start the server under whichever supervisor this generation ships.
if systemctl list-unit-files | grep -q '^helix-p4d'; then
  systemctl enable helix-p4d
  systemctl restart helix-p4d
else
  systemctl enable p4dctl
  p4dctl start "$SERVER_ID"
fi`)))

// applyDefaults fills zero-value fields with module defaults.
// Does not validate required fields — use validate before calling.
func (cfg *UserDataConfig) applyDefaults() {
	if cfg.DataMount == "" {
		cfg.DataMount = "/hxdepots"
	}
	if cfg.ServerID == "" {
		cfg.ServerID = "fabrica-perforce"
	}
	// DataDevice intentionally left empty: the script auto-detects the
	// largest non-root volume, since NVMe enumeration order varies.
}

// validate checks required fields. Call after applyDefaults.
func (cfg *UserDataConfig) validate() error {
	if cfg.AdminPass == "" {
		return fmt.Errorf("AdminPass must not be empty")
	}
	return nil
}

// GenerateRaw renders the cloud-init script without base64 encoding.
// Used in tests to inspect the script content directly.
func GenerateRaw(cfg UserDataConfig) (string, error) {
	if err := userdata.Prepare(cfg.applyDefaults, cfg.validate); err != nil {
		return "", err
	}
	return userDataRenderer.Render(cfg)
}

// Generate renders the cloud-init user data script and returns it base64-encoded
// (the format EC2 expects for UserData in Cloud Control).
func Generate(cfg UserDataConfig) (string, error) {
	if err := userdata.Prepare(cfg.applyDefaults, cfg.validate); err != nil {
		return "", err
	}
	return userDataRenderer.RenderBase64(cfg)
}
