package ami

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"

	"github.com/spf13/cobra"
)

const defaultOutputDir = "ddc-ami"

var (
	amiRE    = regexp.MustCompile(`^ami-[0-9a-f]{8,}$`)
	regionRE = regexp.MustCompile(`^[a-z]{2}-[a-z]+-[0-9]$`)
)

type BuildConfig struct {
	BaseImage string
	Region    string
	Name      string
	OutputDir string
	Backend   string
	DryRun    bool
}

type buildCommand struct {
	out       io.Writer
	cfg       BuildConfig
	writeFile func(path string, data []byte, perm os.FileMode) error
	mkdirAll  func(path string, perm os.FileMode) error
}

func newBuildCmd(out io.Writer) *cobra.Command {
	var cfg BuildConfig
	cmd := &cobra.Command{
		Use:   "build",
		Short: "Generate files needed to build a DDC AMI",
		Long: `Generate local Image Builder artifacts for an Unreal Cloud DDC AMI.

Writes a build-guide.md describing the AMI contract (Jupiter unit, health
endpoints, fabrica.env). No AWS calls. Record the resulting AMI ID in
ddc.amiId / copy it for edge regions.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			c := buildCommand{out: out, cfg: cfg, writeFile: os.WriteFile, mkdirAll: os.MkdirAll}
			return c.run()
		},
	}
	cmd.Flags().StringVar(&cfg.BaseImage, "base-image", "ami-0c7217cdde317cfec", "Base AMI ID")
	cmd.Flags().StringVar(&cfg.Region, "region", "us-east-1", "AWS region")
	cmd.Flags().StringVar(&cfg.Name, "name", "fabrica-ddc", "Image name prefix")
	cmd.Flags().StringVar(&cfg.OutputDir, "output-dir", defaultOutputDir, "Output directory")
	cmd.Flags().StringVar(&cfg.Backend, "backend", "zen", "Documented backend: zen or scylla")
	return cmd
}

func (c buildCommand) run() error {
	if !amiRE.MatchString(c.cfg.BaseImage) {
		return fmt.Errorf("base-image %q is not an AMI id", c.cfg.BaseImage)
	}
	if !regionRE.MatchString(c.cfg.Region) {
		return fmt.Errorf("region %q is invalid", c.cfg.Region)
	}
	if c.cfg.Backend != "zen" && c.cfg.Backend != "scylla" {
		return fmt.Errorf("backend must be zen or scylla, got %q", c.cfg.Backend)
	}
	guide := fmt.Sprintf(`# DDC AMI Build Guide

Generated by `+"`fabrica ddc ami build`"+` for backend **%s** in `+"`%s`"+`.

## Contract

- Base AMI: %s
- systemd unit: unreal-cloud-ddc
- Health: GET /health/ready and GET /health/live on the public port
- Cloud-init writes /etc/unreal-cloud-ddc/fabrica.env (see docs/ddc-ami.md)
- Do not bake credentials or a store

Record the resulting AMI ID as ddc.amiId. Copy it with aws ec2 copy-image
before ddc region add.
`, c.cfg.Backend, c.cfg.Region, c.cfg.BaseImage)
	if c.cfg.DryRun {
		fmt.Fprint(c.out, guide)
		return nil
	}
	dir := c.cfg.OutputDir
	if dir == "" {
		dir = defaultOutputDir
	}
	if err := c.mkdirAll(dir, 0o755); err != nil { // #nosec G301 -- local artifact dir
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	path := filepath.Join(dir, "build-guide.md")
	if err := c.writeFile(path, []byte(guide), 0o644); err != nil { // #nosec G306 -- local guide
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Fprintf(c.out, "Wrote %s. Bake the AMI, then set ddc.amiId.\n", path)
	return nil
}
