#!/usr/bin/env bash
# Generate THIRD_PARTY_NOTICES.txt for release artifacts.
#
# Assembles the redistribution notice file from the current dependency graph:
#   * `go-licenses report` — machine-readable manifest (module, license file,
#     SPDX type)
#   * `go-licenses save`   — the full LICENSE/NOTICE text of every dependency.
#     NOTICE files are a license obligation for aws-sdk-go-v2, smithy-go, and
#     go.yaml.in/yaml/v3 and must travel with redistributions.
#
# Run by the GoReleaser `before` hook at release time and by the CI `licenses`
# job on every PR, so the file is regenerated from the live graph each release
# and never hand-maintained. Fabrica's own LICENSE is excluded (it ships
# separately in the archives and npm package).
set -euo pipefail

OUT="${1:-THIRD_PARTY_NOTICES.txt}"
# Relative work dir (not `mktemp -d`): the `go run` step below may execute a
# Go toolchain that resolves absolute temp paths in a different filesystem
# world than the calling shell (e.g. a WSL bash shim with a Windows Go
# toolchain), so the two could not share /tmp. Relative to the repo root,
# shell and Go always agree.
WORKDIR="./.notices-tmp.$$"
mkdir -p "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT

# `go run` with a pinned version (kept in sync with the CI license gate in
# .github/workflows/ci.yml) avoids $GOPATH/bin PATH assumptions, so the
# script behaves identically on CI (ubuntu), native Windows, and WSL.
gl() { go run github.com/google/go-licenses@v1.6.0 "$@"; }

gl report ./... > "$WORKDIR/report.csv"
gl save ./... --save_path "$WORKDIR/licenses"

{
  echo "# Third-party license and notice manifest"
  echo "#"
  echo "# Generated by scripts/third-party-notices.sh (go-licenses v1.6.0)."
  echo "# Regenerated from the dependency graph on every release and CI run;"
  echo "# do not edit by hand. Fabrica itself is MIT — see LICENSE."
  echo
  echo "## Module manifest (module, license file, license type)"
  grep -v '^github.com/jpvelasco/fabrica,' "$WORKDIR/report.csv"
  echo
  echo "## License and notice text"
} > "$OUT"

(
  cd "$WORKDIR/licenses"
  find . -type f ! -path './github.com/jpvelasco/fabrica/*' | LC_ALL=C sort |
    while IFS= read -r rel; do
      rel="${rel#./}"
      printf '\n# %s\n\n' "$rel"
      cat "$rel"
    done
) >> "$OUT"
