package lore

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"text/template"
)

// UserDataConfig is the input shape for the Lore cloud-init script.
type UserDataConfig struct {
	StorePath string
	ConfigDir string
	GRPCPort  int
	HTTPPort  int
}

var userDataTmpl = template.Must(template.New("lore-userdata").Parse(`#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/fabrica-lore-init.log) 2>&1

STORE="{{ .StorePath }}"
CONFIG_DIR="{{ .ConfigDir }}"

# Resolve the attached EBS data volume for both Xen and Nitro (m5/m7i) paths.
# Xen/older: /dev/sdf or /dev/xvdf.
# Nitro: name is /dev/nvmeXn1 — pick the first NVMe disk that is not the root device.
resolve_data_dev() {
  if [ -b /dev/sdf ]; then
    echo /dev/sdf
    return 0
  fi
  if [ -b /dev/xvdf ]; then
    echo /dev/xvdf
    return 0
  fi

  local root_src root_disk d
  root_src=$(findmnt -n -o SOURCE / 2>/dev/null || true)
  # Strip partition suffix: nvme0n1p1 -> nvme0n1, xvda1 -> xvda, sda1 -> sda
  root_disk=$(echo "$root_src" | sed -E 's/p?[0-9]+$//')

  for d in /dev/nvme*n1; do
    [ -e "$d" ] || continue
    [ -b "$d" ] || continue
    if [ -n "$root_disk" ] && [ "$d" = "$root_disk" ]; then
      continue
    fi
    echo "$d"
    return 0
  done
  return 1
}

DATA_DEV=""
for i in $(seq 1 30); do
  if DATA_DEV=$(resolve_data_dev); then
    break
  fi
  DATA_DEV=""
  if [ "$i" -eq 30 ]; then
    echo "ERROR: data volume not found (checked /dev/sdf, /dev/xvdf, non-root NVMe)"
    exit 1
  fi
  sleep 2
done

echo "Using data device: $DATA_DEV"

mkdir -p "$STORE"
if ! blkid "$DATA_DEV" >/dev/null 2>&1; then
  mkfs.ext4 -F "$DATA_DEV"
fi
if ! mountpoint -q "$STORE"; then
  mount "$DATA_DEV" "$STORE" || true
  if ! mountpoint -q "$STORE"; then
    sleep 2
    mount "$DATA_DEV" "$STORE"
  fi
fi
grep -q "$STORE" /etc/fstab || echo "$DATA_DEV $STORE ext4 defaults,nofail 0 2" >> /etc/fstab

mkdir -p "$STORE/immutable" "$STORE/mutable" "$STORE/lock"
mkdir -p "$CONFIG_DIR"

# Local store config for loreserver (paths only; auth unset in V1).
# Paths are expanded by Fabrica's Go template before cloud-init runs.
cat > "$CONFIG_DIR/local.toml" <<LOREEOF
# Generated by Fabrica — local/EBS store (V1)
[immutable_store]
mode = "local"
path = "{{ .StorePath }}/immutable"

[mutable_store]
mode = "local"
path = "{{ .StorePath }}/mutable"

[lock_store]
mode = "local"
path = "{{ .StorePath }}/lock"
LOREEOF

# Prefer AMI-provided systemd unit; otherwise start loreserver in background
if systemctl list-unit-files 2>/dev/null | grep -q '^loreserver\.service'; then
  systemctl enable loreserver || true
  systemctl restart loreserver
elif command -v loreserver >/dev/null 2>&1; then
  nohup loreserver --config "$CONFIG_DIR" >> /var/log/loreserver.log 2>&1 &
else
  echo "ERROR: loreserver binary or systemd unit not found on AMI"
  exit 1
fi

touch /var/lib/cloud/instance/lore-ready
echo "Lore cloud-init complete (gRPC/QUIC {{ .GRPCPort }}, HTTP {{ .HTTPPort }})"
`))

// GenerateRaw renders the cloud-init script without base64 encoding.
// Used in tests to inspect script content directly.
func GenerateRaw(cfg UserDataConfig) (string, error) {
	if cfg.StorePath == "" {
		cfg.StorePath = DefaultStorePath
	}
	if cfg.ConfigDir == "" {
		cfg.ConfigDir = DefaultConfigDir
	}
	if cfg.GRPCPort <= 0 {
		cfg.GRPCPort = DefaultGRPCPort
	}
	if cfg.HTTPPort <= 0 {
		cfg.HTTPPort = DefaultHTTPPort
	}
	var buf bytes.Buffer
	if err := userDataTmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering userdata template: %w", err)
	}
	return buf.String(), nil
}

// Generate renders the cloud-init script and returns it base64-encoded
// (the format EC2 expects for UserData in Cloud Control).
func Generate(cfg UserDataConfig) (string, error) {
	raw, err := GenerateRaw(cfg)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString([]byte(raw)), nil
}
