// Package credentials provides shared helpers for generating and storing
// per-module credential files under .fabrica/.
package credentials

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"
)

// PasswordChars is the alphabet used by GeneratePassword.
const PasswordChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// GeneratePassword returns a cryptographically random password of the given
// length drawn from PasswordChars (uppercase, lowercase, digits).
func GeneratePassword(length int) (string, error) {
	chars := []byte(PasswordChars)
	out := make([]byte, length)
	for i := range out {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(chars))))
		if err != nil {
			return "", err
		}
		out[i] = chars[n.Int64()]
	}
	return string(out), nil
}

// WriteCredentials creates filepath.Dir(path) (mode 0700) and writes content
// to path with mode 0600. It is intended for module credential YAML files
// stored under .fabrica/.
func WriteCredentials(path string, content string) error {
	dir := filepath.Dir(path)
	// #nosec G301 -- directory needs execute for traversal
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0600)
}

// FormatPerforce returns the YAML content for a Perforce credential file.
func FormatPerforce(adminPassword string) string {
	return fmt.Sprintf("# Perforce admin credentials — keep secret\nadmin_password: %q\n", adminPassword)
}

// ReadFile reads a credential file from disk.
func ReadFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading credentials %s: %w", path, err)
	}
	return string(data), nil
}

// ParsePerforceAdminPassword extracts admin_password from a Perforce
// credentials YAML file written by FormatPerforce.
func ParsePerforceAdminPassword(content string) (string, error) {
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		const key = "admin_password:"
		if !strings.HasPrefix(line, key) {
			continue
		}
		val := strings.TrimSpace(strings.TrimPrefix(line, key))
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		if val == "" {
			return "", fmt.Errorf("admin_password is empty in credentials file")
		}
		return val, nil
	}
	return "", fmt.Errorf("admin_password not found in credentials file — re-run 'fabrica perforce create' or restore .fabrica/perforce-credentials.yaml")
}

// FormatHorde returns the YAML content for a Horde credential file.
func FormatHorde(mongoPassword string) string {
	return fmt.Sprintf("# Horde MongoDB credentials — keep secret\nmongodb_password: %q\nhorde_service_token: \"\"\n", mongoPassword)
}

// FormatLore returns the YAML content for a Lore connection notes file.
// V1 uses self-signed TLS and no JWT; no secrets are generated by Fabrica.
func FormatLore(grpcPort, httpPort int) string {
	return fmt.Sprintf(`# Lore server connection notes (V1)
# Auth is unset; TLS is self-signed on the instance. Clients must trust the
# server cert or use the client's insecure / skip-verify option.
grpc_port: %d   # TCP gRPC + UDP QUIC
http_port: %d   # HTTP health: GET /health_check
`, grpcPort, httpPort)
}
